### ISSUE TITLE
SD card issue, missing flush method

### ISSUE THREAD

**Issue by h3lpd3sk** [RobTillaart/Multiplex#13] opened 2022-10-23 09:36 UTC
I could not get the SD card example working. 
After some investigation I noticed you are required to call flush() or close() to actually write the buffer to the file.
So I added multiplex.flush(); calls. 
To find this didn't work as this method is not implemented.

So I added Multiplex.h:
`  virtual void flush() override;`

And Multiplex.cpp:
`void Multiplex::flush()
{
  for (uint8_t i = 0; i < _count; i++)
  {
    if (_enabled[i])
    {
      _stream[i]->flush();
    }
  }
}`

After which everything works as expected. 

If you grant me access I can push the PR or feel free to implement it yourself.

**Comment by RobTillaart** [comment] 2022-10-23 09:57
Thanks for the issue. (Good catch)

If you fork the repo you can always create a PR.
Better I will pick it up later this week, I am busy adding RP2040 builds to all my repos so I can add that in one go. 

Btw your proposal looks ok.

**Comment by RobTillaart** [comment] 2022-10-23 10:25
@h3lpd3sk 
A new develop branch will be available asap. 
update: 
- branch created..
- fix minors in readme.md

**Comment by RobTillaart** [comment] 2022-10-23 10:53
@h3lpd3sk 
Do you have time to verify the develop branch?
If ok I will merge and release 0.2.5

**Comment by h3lpd3sk** [comment] 2022-10-23 11:39
@RobTillaart 
Develop branch resolves the issue indeed! Thanks for your swift action.

I should contribute more to opensource perhaps. 
Thanks for pointing out the Fork workflow, I wasn't familiar with it yet.

**Comment by RobTillaart** [comment] 2022-10-23 12:09
> I should contribute more to opensource perhaps.

One advantage is that bugs are caught by others, sometimes ones you would never imagine. 
On the feature side too, capturing (part of) your code into a library can make your projects richer as other people request features / enhancements that you can use into your own projects. 
And last but not least it is fun. 
Fun to create and fun to see where your code lands eventually, in fact I get feedback / request from all over the world. Would be nice to see my code also go into space e.g. with a cube satellite, but that has not been confirmed yet.

> Thanks for pointing out the Fork workflow, I wasn't familiar with it yet.

Just give it a try on this library to see how things work. (please mention it is a test :)

**Comment by RobTillaart** [comment] 2022-10-24 08:18
As the issue is solved, I close it. Feel free to reopen / create an new one if needed.

**Closed as completed by RobTillaart** 2022-10-24 08:18 UTC
Labels: bug
